def remote = [:]
remote.name = "labs"
remote.host = "athenslabs.gr"
remote.allowAnyHosts = true

pipeline {
    agent {
        docker {
            image 'node:lts-alpine'
            args '-p 3000:3000 -p 5000:5000'
        }
    }
    environment {
        CI = 'true'
        SSH_CREDS = credentials('cbf9acb1-da9a-4409-9812-3bede055c082')
        remote.user = SSH_CREDS_USR
        remote.identityFile = SSH_CREDS
        remote.port = 9122
    }
    stages {
        stage('Build') {
            steps {
                sshCommand remote: remote, command: 'for i in {1..5}; do echo -n \"Loop \$i \"; date ; sleep 1; done'
                sh 'npm install'

            }
        }
        stage('Test') {
            steps {
                sh './jenkins/scripts/test.sh'
            }
        }
        stage('Deliver for development') {
            when {
                branch 'development'
            }
            steps {
                sh './jenkins/scripts/deliver-for-development.sh'
                input message: 'Finished using the web site? (Click "Proceed" to continue)'
                sh './jenkins/scripts/kill.sh'
            }
        }
        stage('Deploy for production') {
            when {
                branch 'production'
            }
            steps {
                sh './jenkins/scripts/deploy-for-production.sh'
                input message: 'Finished using the web site? (Click "Proceed" to continue)'
                sh './jenkins/scripts/kill.sh'
            }
        }
    }
}
